# -*- coding: utf-8 -*-
"""5.3 exercise

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15wnAIFSvM8EwIUAuNmSvuQCWT3pOFX8b
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.formula.api import ols, glm
import numpy as np
from IPython import display

# Data Import
raw_data = pd.read_csv('/content/drive/MyDrive/student_math_grades.csv')
raw_data.head(2)

# Sanity Check
print("Shape: " + str(raw_data.shape))
SC = []
for i in raw_data.columns:
  SC.append(raw_data[i].value_counts())
print(SC)

# Data Cleaning
raw_data['school'].replace({"GP":1, "MS":0}, inplace = True)
raw_data['sex'].replace({"M":1, "F":0}, inplace = True)
raw_data['address'].replace({"U":1, "R":0}, inplace = True)
raw_data['famsize'].replace({"LE3":1, "GT3":0}, inplace = True)
raw_data['pstatus'].replace({"T":1, "A":0}, inplace = True)
raw_data['schoolsup'].replace({"yes":1, "no":0}, inplace = True)
raw_data['famsup'].replace({"yes":1, "no":0}, inplace = True)
raw_data['paid'].replace({"yes":1, "no":0}, inplace = True)
raw_data['activities'].replace({"yes":1, "no":0}, inplace = True)
raw_data['nursery'].replace({"yes":1, "no":0}, inplace = True)
raw_data['higher'].replace({"yes":1, "no":0}, inplace = True)
raw_data['internet'].replace({"yes":1, "no":0}, inplace = True)
df = pd.concat([raw_data, pd.get_dummies(raw_data['mjob'], prefix = 'm', drop_first=True)], axis = 1)
df = pd.concat([df, pd.get_dummies(raw_data['fjob'], prefix = 'f', drop_first=True)], axis = 1)
df = pd.concat([df, pd.get_dummies(raw_data['reason'], prefix = 'reason', drop_first=True)], axis = 1)
df = pd.concat([df, pd.get_dummies(raw_data['guardian'], prefix = 'guardian', drop_first=True)], axis = 1)
df.drop(columns = ['mjob', 'fjob', 'reason', 'guardian'], inplace = True)

"""***Linear Reg - Backward Stepwise Regression***"""

# Linear Reg - Backward Stepwise Regression.
mod0 = ols('grades ~ medu + failures', data = df).fit()
print(mod0.summary())

"""Adj. R-squared: 0.144 is low in terms of Marketing, but ***acceptable*** in Sociology.

**Falk and Miller (1992)** recommended that R2 values should be equal to or greater than 0.10 for the variance explained of a particular endogenous construct to be deemed adequate.
**Cohen (1988)** suggested R2 values for endogenous latent variables are assessed as follows: 0.26 (substantial), 0.13 (moderate), 0.02 (weak). 

*The there’s only one variable having a negative impact on the outcome, “failures”, which means number of past class failures. It indicates that the number of past class failures causes final failure.*

*Based on the model above, the there’s two variable having significant impact on the outcome, “medu” and “failures”.*

*According to the attribute information, we know the mother's education is out of control. Therefore, the only way is decreasing the number of past class failures of students.*

**OR% in Logistic Regressiona**
"""

df['grades'].replace({20:1, 19:1, 18:1, 17:1, 16:1, 15:1, 14:1, 13:1, 
                              12:1, 11:1, 10:1, 9:1, 8:1, 7:1, 6:0, 5:1, 4:1,
                              3:1, 2:1, 1:0}, inplace = True)
df['grades'].head()

mod1 = glm('grades ~ school + sex + age + address + famsize + pstatus + medu + fedu + \
traveltime + studytime + failures + schoolsup + famsup + paid + activities + \
nursery + higher + internet + famrel + freetime + goout + dalc + walc + health \
+ absences + m_health + m_other + m_services + m_teacher + f_health + f_other + \
f_services + f_teacher + reason_home + reason_other + reason_reputation + \
guardian_mother + guardian_other', data = df).fit()
print(mod1.summary())

# OR%
(np.exp(mod1.params)-1) * 100